name: Test and Build Node.js Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify your desired Node.js version

    - name: Install dependencies
      run: make install  # This runs npm install via your Makefile

    - name: Run the application
      run: |
        make run &
        sleep 5  # Give time for the server to start

    - name: Verify application is running
      run: curl http://localhost:3000
